### ISSUE TITLE
Can't register two SqlServer liveness

### ISSUE THREAD

**Issue by eiximenis** [Xabaril/BeatPulse#21] opened 2018-04-06 09:06 UTC
Trying to add two SqlServer liveness:

```
context.AddSqlServer("the-sql-server-connection-string");
context.AddSqlServer("the-sql-server-connection-string-2");
```

Generates an error complaining about the "sqlserver" path is already registered

**Comment by Xabaril** [comment] 2018-04-06 09:59
Related with #22 
The issue is present and this solve it, but at this moment you need to implement this feature in all liveness. Probably is good to review the design to move this behavior into the LivenessContext instead on all liveness

**Comment by eiximenis** [comment] 2018-04-06 13:49
Ok.
I can provide a PR to solve the problem gradually. Only that will take a bit longer :)

**Comment by unaizorrilla** [comment] 2018-05-10 21:27
Fixed on 3537ca9c5a9a7563c73911c25b9021883e7b252d

**Closed by unaizorrilla** 2018-05-10 21:27 UTC
Labels: bug, enhancement
